#! /bin/bash

# get PLUMED version
source ../sourceme.sh
PROJECT_NUMBER=`../src/lib/plumed --no-mpi info --long-version`
# check if master
if [[ "$PROJECT_NUMBER" == *"dev"* ]]; then
 PROJECT_NUMBER="development version"
else
 PROJECT_NUMBER=v$PROJECT_NUMBER
fi

for file in html/*.html
do
 # color PLUMED syntax
 awk -f plumed-syntax-mcss.awk $file > $file.tmp
 # add developer manual
 sed -e "s/Manual<\/a>/Manual<\/a> <span class=\"m-breadcrumb\">|<\/span> <a class=\"m-breadcrumb\">$PROJECT_NUMBER<\/a> <a href=\"..\/..\/developer-doc\/html\/index.html\" class=\"m-thin m-right-m\"\>Developer Manual<\/a>/g" $file.tmp > $file
 rm $file.tmp
done
