#! /bin/bash

# Making sure that plumed executable is available
echo -n "Searching for plumed ..."
if plumed 2>/dev/null 1>/dev/null ; then
  echo " found"
else
  echo " not found"
  echo -n "Sourcing sourceme.sh and searching again ..."
  if source ../sourceme.sh && plumed 2>/dev/null 1>/dev/null ; then
    echo " found"
  else
    echo "ERROR: you should compile plumed first!"
    exit 1
  fi
fi

LIST="
 IntroPP.txt ../CHANGES InstallationPP.txt SyntaxPP.txt ColvarPP.txt GroupPP.txt FunctionsPP.txt AnalysisPP.txt
  BiasPP.txt ToolsPP.txt MiscPP.txt RegexPP.txt ModulesPP.txt TutorialsPP.txt GlossaryPP.txt automatic tutorials"

{
  cat Doxyfile
  echo "PROJECT_NUMBER = \"$(plumed info --long-version)\""
  echo "INPUT+=" $LIST
  # add this to manually control layout:
  # echo "LAYOUT_FILE=PlumedLayout.xml"
} | doxygen -

cd latex

# this is a workaround for a problem on the linux workstation
# where I compile the manual - GB
sed -i 's/pdfencoding=unicode/unicode/g' refman.tex
make
cp refman.pdf ../manual.pdf

