USE=asmjit

# generic makefile
include ../maketools/make.module
#code here is not "ours", so no -Werror
#this gives some problems in ParsedExpression.cpp with a few -Wmaybe-uninitialized that looks to me as false positives
#most probles are -Wsign-compare
#CXXFLAGS:= $(CXXFLAGS) -Wshadow -Werror
