#! /usr/bin/env bash

confirm () {
    # call with a prompt string or use a default
    read -r -p "${1:-Are you sure? [y/N]} " response
    case $response in
        [yY][eE][sS]|[yY])
            true
            ;;
        *)
            false
            ;;
    esac
}

confirm "Are you shure that you want to Uninstall? This might lead to data loss! [y/N]" || exit 1


