#! /bin/bash
# copy the listed objects to prefix giving them a progressive number
# e.g.
# copyobjects pippo/k a/a.o b/b.o c/c.o
# becomes
# cp a/a.o pippo/k0.o
# cp b/b.o pippo/k1.o
# cp c/c.o pippo/k2.o

prefix="$1"

shift

i=0
for file in "$@"
do
  cp "$file" "$prefix$i.o"
  i=$((i+1))
done
