#
# This is a generic makefile which will work for any
# subpackage which just depends on config/
# It just compiles objects locally
# 

# include the machine dependent configuration
-include ../../Makefile.conf

# if machine dependent configuration has been found:
ifdef GCCDEP

# source for plumed kernel
SRC=$(wildcard *.cpp)

# corresponding objects:
OBJ=$(SRC:.cpp=.o)

# dependency files for all c++ sources
DEP=$(addprefix deps/,$(SRC:.cpp=.d))

.PHONY: all links dirslinks obj lib install

# default target:
# update all links then build this module
all: dirslinks
	@echo Preparing for make
	$(PREMAKE)
	@echo "*** Compile local objects ***"
	$(MAKE) obj

# build links for this module
links: Makefile
	@echo Verify modules and create links in $(CURDIR)
	@for dir in $(USE) ; do ../maketools/check_module.sh $$dir ; ../maketools/makelinks.sh $$dir ;  done

# build links for all modules
dirslinks:
	make -C ../lib dirslinks

# buils objects in this module
obj: $(OBJ)

# build everything
lib:
	cd ../lib ; make

.PHONY: install
install:
	cd ../lib ; make install

-include $(DEP)

# if machine dependent configuration has not been found:
else

.PHONY: error
error:
	@echo No configuration available
	@echo First run ./configure in the root directory
endif

# this target is available anyway

.PHONY: clean
clean:
	@echo Clean $(CURDIR)
	../maketools/cleanlinks.sh
	rm -fr deps links
	rm -f $(CLEANLIST)

# generic makefile rules
include ../maketools/make.rules

