#!/bin/bash

nerror=0
nok=0
notapp=0

echo
echo
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Test session ended at $(date)"

for file in rt*/report.txt
do
  if grep -q NOT_APPLIABLE $file ; then
    ((notapp++))
    echo + test ${file%/report.txt} NOT APPLIABLE
    echo + check file $file for more information
  elif grep -q FAILURE $file ; then
    ((nerror++))
    echo + ERROR in test ${file%/report.txt}
    echo + check file $file for more information
  else
    ((nok++))
  fi
done

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Final report:"
echo "+ $((nok+nerror)) tests performed, $notapp tests not appliable"
echo "+ $nerror errors found"
if ((nerror==0)) ; then
echo "+ Well done!!"
else
echo "+ Find the bug!"
echo "+ To replace references, go to the test directory and"
echo "+ type 'make reset'"
fi
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo

