#!/bin/bash

N=0
M=0

echo
echo
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Test session ended at $(date)"

for file in rt*/report.txt
do
  ((M++))
  grep -q FAILURE $file &&
{
  ((N++))
  echo + ERROR in test ${file%/report.txt}
  echo + check file $file for more information
}
done

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Final report:"
echo "+ $M tests performed, $N errors found"
if ((N==0)) ; then
echo "+ Well done!!"
else
echo "+ Find the bug!"
echo "+ To replace references, go to the test directory and"
echo "+ type 'make reset'"
fi
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo

