#!/bin/bash

for action in $(
  cat $(plumed info --root)/src/*/*.cpp |  grep PLUMED_REGISTER_ACTION |
  sed -e 's/,/ /g
          s/(/ /g
          s/)/ /g' | awk '{print $3}' | sed -e 's/\([\"]\)//g'
)
do
  if  ! grep -q $action */rt*/plumed.dat
  then
    echo "WARNING : There are no regtests for action $action"
  fi
done

