#! /bin/bash
# first check if PLUMED_ROOT is set
echo "+++ PLUMED tool +++"
if [ -z "$PLUMED_ROOT" ]
then
  echo "ERROR: I cannot find PLUMED"
  echo "Please set PLUMED_ROOT environment variable"
  exit
fi
if [ ! -d "$PLUMED_ROOT/patches/" ]
then
  echo "ERROR: cannot find $PLUMED_ROOT/patches/ directory"
  echo "Check your PLUMED_ROOT variable"
  exit
fi

echo "+++ PLUMED_ROOT=$PLUMED_ROOT +++"

export PLUMED_ROOT

prefix=""
action=""
exitloop=""

while [ -n "$*" ]
do

  prefix_option="$prefix$1"
  prefix=""

  case "$prefix_option" in
    (help|--help|-h)    action=help;   exitloop=yes ;;
    (-*)                
      echo "ERROR: Unknown option $prefix_option. Use 'plumed help' for help"
      exit ;;
    (*)                 action=$prefix_option;  exitloop=yes ;;
  esac
  shift

  test -n "$exitloop" && break
done

if [ -z "$action" ] ; then
  echo "Nothing to do. Use 'plumed help' for help"
  exit
fi

if [ "$action" == "help" ]
then
  echo "Usage: plumed [action] [options]"
  echo "  plumed help: to print this help"
  echo "  plumed [action] -h: to print help for a specific action"
  echo
  for file in $PLUMED_ROOT/tools/scripts/*.sh
  do
    name=${file##*/}
    name=${name%.sh}
    echo "  plumed $name:" $( $file --description)
  done
  exit 0
fi

if [ -x "${PLUMED_ROOT}/tools/scripts/$action.sh" ] ; then
  "${PLUMED_ROOT}/tools/scripts/$action.sh" "$@"
else
  echo "ERROR: Unknown action $action. Use 'plumed help' for help"
  exit
fi



