USE=core lapack lepton small_vector xdrfile molfile

# generic makefile
include ../maketools/make.module

# -Wshadows helps to find slips in the code, 
# -Werror makes fixing warnings mandatory
CXXFLAGS:= $(CXXFLAGS) -Wshadow -Werror

